import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { LatopEntryTable } from '../components/LaptopEntryTable'
import NotebookcheckLaptop, { LaptopEntry } from '../services/notebookcheckLaptop'

interface HomeProps {
  // _notebookCheck: NotebookcheckLaptop
  _laptopEntries: Array<LaptopEntry>
}

const Home: NextPage<HomeProps> = ({ _laptopEntries}: HomeProps ) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Laptop Benchmark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Laptop Benchmark!
        </h1>

        <LatopEntryTable laptops={_laptopEntries}  />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  let notebook = new NotebookcheckLaptop()

  return {
    props: {
      // _notebookCheck: notebook,
      _laptopEntries: await notebook.getDefaultLaptops()
    }
  }
}

export default Home
